-- Add new values to ProspectStatus enum
ALTER TYPE "ProspectStatus" ADD VALUE IF NOT EXISTS 'CLAIMED_REQUEST';
ALTER TYPE "ProspectStatus" ADD VALUE IF NOT EXISTS 'FULFILLED';
ALTER TYPE "ProspectStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE "ProspectStatus" ADD VALUE IF NOT EXISTS 'BOUNCED';
ALTER TYPE "ProspectStatus" ADD VALUE IF NOT EXISTS 'UNSUBSCRIBED';
