// app/sys-2847/fleet/constants.ts

import { CarCategory, CarStatus, TransmissionType, FuelType } from './types'

export const CAR_CATEGORIES = [
  { value: CarCategory.LUXURY, label: 'Luxury' },
  { value: CarCategory.EXOTIC, label: 'Exotic' },
  { value: CarCategory.SPORTS, label: 'Sports' },
  { value: CarCategory.SUV, label: 'SUV' },
  { value: CarCategory.ELECTRIC, label: 'Electric' },
  { value: CarCategory.CONVERTIBLE, label: 'Convertible' },
  { value: CarCategory.SEDAN, label: 'Sedan' }
]

export const CAR_STATUSES = [
  { value: CarStatus.AVAILABLE, label: 'Available', color: 'green' },
  { value: CarStatus.BOOKED, label: 'Booked', color: 'blue' },
  { value: CarStatus.MAINTENANCE, label: 'Maintenance', color: 'yellow' },
  { value: CarStatus.PENDING_INSPECTION, label: 'Pending Inspection', color: 'orange' },
  { value: CarStatus.UNLISTED, label: 'Unlisted', color: 'gray' },
  { value: CarStatus.RETIRED, label: 'Retired', color: 'red' }
]

export const TRANSMISSION_TYPES = [
  { value: TransmissionType.AUTOMATIC, label: 'Automatic' },
  { value: TransmissionType.MANUAL, label: 'Manual' },
  { value: TransmissionType.SEMI_AUTOMATIC, label: 'Semi-Automatic' }
]

export const FUEL_TYPES = [
  { value: FuelType.PREMIUM, label: 'Premium' },
  { value: FuelType.REGULAR, label: 'Regular' },
  { value: FuelType.ELECTRIC, label: 'Electric' },
  { value: FuelType.HYBRID, label: 'Hybrid' },
  { value: FuelType.DIESEL, label: 'Diesel' }
]

export const DEFAULT_HOST_IDS = [
  { id: 'host_001', name: 'Erick Nick', email: 'erick@example.com' },
  { id: 'host_002', name: 'Jenny Wilson', email: 'jenny.wilson@example.com' },
  { id: 'host_003', name: 'Michael Chen', email: 'michael@example.com' },
  { id: 'host_004', name: 'Sarah Williams', email: 'sarah@example.com' },
  { id: 'host_005', name: 'Phoenix Auto Group', email: 'group@example.com' },
  { id: 'host_006', name: 'Desert Drive Collection', email: 'desert@example.com' },
  { id: 'host_007', name: 'Robert Johnson', email: 'robert.j@example.com' },
  { id: 'host_008', name: 'Maria Garcia', email: 'maria.g@example.com' },
  { id: 'host_009', name: 'David Martinez', email: 'david.m@example.com' },
  { id: 'host_010', name: 'Jennifer Lee', email: 'jennifer.lee@example.com' },
  { id: 'host_011', name: 'James Smith', email: 'james.smith@example.com' },
  { id: 'host_012', name: 'Emily Brown', email: 'emily.brown@example.com' },
  { id: 'host_013', name: 'Daniel White', email: 'daniel.white@example.com' },
  { id: 'host_014', name: 'Jessica Taylor', email: 'jessica.taylor@example.com' },
  { id: 'host_015', name: 'Christopher Davis', email: 'chris.davis@example.com' },
  { id: 'host_016', name: 'Ashley Anderson', email: 'ashley.a@example.com' },
  { id: 'host_017', name: 'Matthew Thomas', email: 'matt.thomas@example.com' },
  { id: 'host_018', name: 'Amanda Jackson', email: 'amanda.j@example.com' },
  { id: 'host_019', name: 'Joshua Martin', email: 'joshua.martin@example.com' },
  { id: 'host_020', name: 'Stephanie Miller', email: 'stephanie.m@example.com' },
  { id: 'host_021', name: 'Andrew Wilson', email: 'andrew.wilson@example.com' },
  { id: 'host_022', name: 'Nicole Moore', email: 'nicole.moore@example.com' },
  { id: 'host_023', name: 'Ryan Thompson', email: 'ryan.t@example.com' },
  { id: 'host_024', name: 'Michelle Harris', email: 'michelle.h@example.com' },
  { id: 'host_025', name: 'Kevin Clark', email: 'kevin.clark@example.com' },
  { id: 'host_026', name: 'Laura Lewis', email: 'laura.lewis@example.com' },
  { id: 'host_027', name: 'Brian Robinson', email: 'brian.r@example.com' },
  { id: 'host_028', name: 'Samantha Walker', email: 'sam.walker@example.com' },
  { id: 'host_029', name: 'Justin Hall', email: 'justin.hall@example.com' },
  { id: 'host_030', name: 'Rachel Young', email: 'rachel.young@example.com' },
  { id: 'host_031', name: 'Brandon King', email: 'brandon.king@example.com' },
  { id: 'host_032', name: 'Megan Wright', email: 'megan.wright@example.com' },
  { id: 'host_033', name: 'Eric Lopez', email: 'eric.lopez@example.com' },
  { id: 'host_034', name: 'Katherine Hill', email: 'katherine.h@example.com' },
  { id: 'host_035', name: 'Steven Scott', email: 'steven.scott@example.com' },
  { id: 'host_036', name: 'Christina Green', email: 'christina.g@example.com' },
  { id: 'host_037', name: 'Tyler Adams', email: 'tyler.adams@example.com' },
  { id: 'host_038', name: 'Lauren Baker', email: 'lauren.baker@example.com' },
  { id: 'host_039', name: 'Aaron Nelson', email: 'aaron.nelson@example.com' },
  { id: 'host_040', name: 'Brittany Carter', email: 'brittany.c@example.com' },
  { id: 'host_041', name: 'Alexander Mitchell', email: 'alex.mitchell@example.com' },
  { id: 'host_042', name: 'Danielle Perez', email: 'danielle.p@example.com' },
  { id: 'host_043', name: 'Nathan Roberts', email: 'nathan.r@example.com' },
  { id: 'host_044', name: 'Victoria Turner', email: 'victoria.t@example.com' },
  { id: 'host_045', name: 'Jordan Phillips', email: 'jordan.p@example.com' },
  { id: 'host_046', name: 'Kayla Campbell', email: 'kayla.c@example.com' },
  { id: 'host_047', name: 'Austin Parker', email: 'austin.parker@example.com' },
  { id: 'host_048', name: 'Hannah Evans', email: 'hannah.evans@example.com' },
  { id: 'host_049', name: 'Zachary Edwards', email: 'zach.edwards@example.com' },
  { id: 'host_050', name: 'Olivia Collins', email: 'olivia.collins@example.com' },
  { id: 'host_051', name: 'Gabriel Stewart', email: 'gabriel.s@example.com' },
  { id: 'host_052', name: 'Sophia Sanchez', email: 'sophia.s@example.com' },
  { id: 'host_053', name: 'Logan Morris', email: 'logan.morris@example.com' },
  { id: 'host_054', name: 'Emma Rogers', email: 'emma.rogers@example.com' },
  { id: 'host_055', name: 'Jacob Reed', email: 'jacob.reed@example.com' },
  { id: 'host_056', name: 'Isabella Cook', email: 'isabella.cook@example.com' },
  { id: 'host_057', name: 'Ethan Morgan', email: 'ethan.morgan@example.com' },
  { id: 'host_058', name: 'Madison Bell', email: 'madison.bell@example.com' },
  { id: 'host_059', name: 'Mason Murphy', email: 'mason.murphy@example.com' },
  { id: 'host_060', name: 'Ava Bailey', email: 'ava.bailey@example.com' },
  { id: 'host_061', name: 'William Rivera', email: 'william.r@example.com' },
  { id: 'host_062', name: 'Charlotte Cooper', email: 'charlotte.c@example.com' },
  { id: 'host_063', name: 'Jayden Richardson', email: 'jayden.r@example.com' },
  { id: 'host_064', name: 'Amelia Cox', email: 'amelia.cox@example.com' },
  { id: 'host_065', name: 'Noah Howard', email: 'noah.howard@example.com' },
  { id: 'host_066', name: 'Harper Ward', email: 'harper.ward@example.com' },
  { id: 'host_067', name: 'Lucas Torres', email: 'lucas.torres@example.com' },
  { id: 'host_068', name: 'Evelyn Peterson', email: 'evelyn.p@example.com' },
  { id: 'host_069', name: 'Benjamin Gray', email: 'benjamin.gray@example.com' },
  { id: 'host_070', name: 'Abigail Ramirez', email: 'abigail.r@example.com' },
  { id: 'host_071', name: 'Elijah James', email: 'elijah.james@example.com' },
  { id: 'host_072', name: 'Elizabeth Watson', email: 'elizabeth.w@example.com' },
  { id: 'host_073', name: 'Sebastian Brooks', email: 'sebastian.b@example.com' },
  { id: 'host_074', name: 'Mia Kelly', email: 'mia.kelly@example.com' },
  { id: 'host_075', name: 'Aiden Sanders', email: 'aiden.sanders@example.com' },
  { id: 'host_076', name: 'Ella Price', email: 'ella.price@example.com' },
  { id: 'host_077', name: 'Jackson Bennett', email: 'jackson.b@example.com' },
  { id: 'host_078', name: 'Grace Wood', email: 'grace.wood@example.com' },
  { id: 'host_079', name: 'Carter Barnes', email: 'carter.barnes@example.com' },
  { id: 'host_080', name: 'Chloe Ross', email: 'chloe.ross@example.com' },
  { id: 'host_081', name: 'Caleb Henderson', email: 'caleb.h@example.com' },
  { id: 'host_082', name: 'Zoey Coleman', email: 'zoey.coleman@example.com' },
  { id: 'host_083', name: 'Hunter Jenkins', email: 'hunter.jenkins@example.com' },
  { id: 'host_084', name: 'Lily Perry', email: 'lily.perry@example.com' },
  { id: 'host_085', name: 'Christian Powell', email: 'christian.p@example.com' },
  { id: 'host_086', name: 'Natalie Long', email: 'natalie.long@example.com' },
  { id: 'host_087', name: 'Isaac Patterson', email: 'isaac.patterson@example.com' },
  { id: 'host_088', name: 'Addison Hughes', email: 'addison.h@example.com' },
  { id: 'host_089', name: 'Isaiah Flores', email: 'isaiah.flores@example.com' },
  { id: 'host_090', name: 'Aubrey Washington', email: 'aubrey.w@example.com' },
  { id: 'host_091', name: 'Julian Butler', email: 'julian.butler@example.com' },
  { id: 'host_092', name: 'Lillian Foster', email: 'lillian.foster@example.com' },
  { id: 'host_093', name: 'Luke Gonzalez', email: 'luke.gonzalez@example.com' },
  { id: 'host_094', name: 'Hannah Bryant', email: 'hannah.bryant@example.com' },
  { id: 'host_095', name: 'Oliver Alexander', email: 'oliver.a@example.com' },
  { id: 'host_096', name: 'Zoe Russell', email: 'zoe.russell@example.com' },
  { id: 'host_097', name: 'Eli Griffin', email: 'eli.griffin@example.com' },
  { id: 'host_098', name: 'Layla Diaz', email: 'layla.diaz@example.com' },
  { id: 'host_099', name: 'Levi Hayes', email: 'levi.hayes@example.com' },
  { id: 'host_100', name: 'Victoria Myers', email: 'victoria.myers@example.com' },
  // Adding 100 more hosts
  { id: 'host_101', name: 'Phoenix Luxury Rentals', email: 'luxury@example.com' },
  { id: 'host_102', name: 'Scottsdale Elite Cars', email: 'elite@example.com' },
  { id: 'host_103', name: 'Adrian Foster', email: 'adrian.f@example.com' },
  { id: 'host_104', name: 'Brooke Sullivan', email: 'brooke.s@example.com' },
  { id: 'host_105', name: 'Cole Maxwell', email: 'cole.maxwell@example.com' },
  { id: 'host_106', name: 'Diana Pierce', email: 'diana.pierce@example.com' },
  { id: 'host_107', name: 'Felix Graham', email: 'felix.graham@example.com' },
  { id: 'host_108', name: 'Gabriella Stone', email: 'gabriella.s@example.com' },
  { id: 'host_109', name: 'Henry Walsh', email: 'henry.walsh@example.com' },
  { id: 'host_110', name: 'Iris Montgomery', email: 'iris.m@example.com' },
  { id: 'host_111', name: 'Jake Fleming', email: 'jake.fleming@example.com' },
  { id: 'host_112', name: 'Kimberly Day', email: 'kimberly.day@example.com' },
  { id: 'host_113', name: 'Leo Bates', email: 'leo.bates@example.com' },
  { id: 'host_114', name: 'Maya Davidson', email: 'maya.davidson@example.com' },
  { id: 'host_115', name: 'Nicholas Webb', email: 'nicholas.webb@example.com' },
  { id: 'host_116', name: 'Paige Simpson', email: 'paige.simpson@example.com' },
  { id: 'host_117', name: 'Quinn Richards', email: 'quinn.richards@example.com' },
  { id: 'host_118', name: 'Ruby Chapman', email: 'ruby.chapman@example.com' },
  { id: 'host_119', name: 'Samuel Lawrence', email: 'samuel.l@example.com' },
  { id: 'host_120', name: 'Tessa Reynolds', email: 'tessa.reynolds@example.com' },
  { id: 'host_121', name: 'Ulysses Grant', email: 'ulysses.g@example.com' },
  { id: 'host_122', name: 'Violet Hunter', email: 'violet.hunter@example.com' },
  { id: 'host_123', name: 'Wesley Shaw', email: 'wesley.shaw@example.com' },
  { id: 'host_124', name: 'Xander Cruz', email: 'xander.cruz@example.com' },
  { id: 'host_125', name: 'Yasmine Ali', email: 'yasmine.ali@example.com' },
  { id: 'host_126', name: 'Zane Morrison', email: 'zane.morrison@example.com' },
  { id: 'host_127', name: 'Alice Carpenter', email: 'alice.carpenter@example.com' },
  { id: 'host_128', name: 'Blake Hudson', email: 'blake.hudson@example.com' },
  { id: 'host_129', name: 'Clara Miles', email: 'clara.miles@example.com' },
  { id: 'host_130', name: 'Dean Fletcher', email: 'dean.fletcher@example.com' },
  { id: 'host_131', name: 'Eva Norton', email: 'eva.norton@example.com' },
  { id: 'host_132', name: 'Finn O\'Brien', email: 'finn.obrien@example.com' },
  { id: 'host_133', name: 'Gina Lawson', email: 'gina.lawson@example.com' },
  { id: 'host_134', name: 'Hector Mendoza', email: 'hector.m@example.com' },
  { id: 'host_135', name: 'Ivy Chen', email: 'ivy.chen@example.com' },
  { id: 'host_136', name: 'Jasper Knight', email: 'jasper.knight@example.com' },
  { id: 'host_137', name: 'Kelly Quinn', email: 'kelly.quinn@example.com' },
  { id: 'host_138', name: 'Lance Wolfe', email: 'lance.wolfe@example.com' },
  { id: 'host_139', name: 'Monica Blair', email: 'monica.blair@example.com' },
  { id: 'host_140', name: 'Neil Frost', email: 'neil.frost@example.com' },
  { id: 'host_141', name: 'Oscar Reyes', email: 'oscar.reyes@example.com' },
  { id: 'host_142', name: 'Penelope Cross', email: 'penelope.c@example.com' },
  { id: 'host_143', name: 'Quincy Banks', email: 'quincy.banks@example.com' },
  { id: 'host_144', name: 'Rose Caldwell', email: 'rose.caldwell@example.com' },
  { id: 'host_145', name: 'Seth Warner', email: 'seth.warner@example.com' },
  { id: 'host_146', name: 'Tara Singh', email: 'tara.singh@example.com' },
  { id: 'host_147', name: 'Uma Patel', email: 'uma.patel@example.com' },
  { id: 'host_148', name: 'Vincent Black', email: 'vincent.black@example.com' },
  { id: 'host_149', name: 'Willow Green', email: 'willow.green@example.com' },
  { id: 'host_150', name: 'Xavier Luna', email: 'xavier.luna@example.com' },
  { id: 'host_151', name: 'Yara Hassan', email: 'yara.hassan@example.com' },
  { id: 'host_152', name: 'Zeus Powers', email: 'zeus.powers@example.com' },
  { id: 'host_153', name: 'Desert Drives LLC', email: 'drives@example.com' },
  { id: 'host_154', name: 'Valley Motor Group', email: 'valley@example.com' },
  { id: 'host_155', name: 'Premium Fleet AZ', email: 'premium@example.com' },
  { id: 'host_156', name: 'Luxury Lane Phoenix', email: 'luxurylane@example.com' },
  { id: 'host_157', name: 'Elite Auto Experience', email: 'eliteauto@example.com' },
  { id: 'host_158', name: 'Prestige Car Collection', email: 'prestige@example.com' },
  { id: 'host_159', name: 'Metro Motors Phoenix', email: 'metro@example.com' },
  { id: 'host_160', name: 'Apex Auto Rentals', email: 'apex@example.com' },
  { id: 'host_161', name: 'Bella Romano', email: 'bella.r@example.com' },
  { id: 'host_162', name: 'Charlie Nash', email: 'charlie.nash@example.com' },
  { id: 'host_163', name: 'Derek Stone', email: 'derek.stone@example.com' },
  { id: 'host_164', name: 'Elena Vargas', email: 'elena.vargas@example.com' },
  { id: 'host_165', name: 'Frank Castle', email: 'frank.castle@example.com' },
  { id: 'host_166', name: 'Georgia Wells', email: 'georgia.wells@example.com' },
  { id: 'host_167', name: 'Hugo Martinez', email: 'hugo.martinez@example.com' },
  { id: 'host_168', name: 'Ingrid Hansen', email: 'ingrid.hansen@example.com' },
  { id: 'host_169', name: 'Joel Cooper', email: 'joel.cooper@example.com' },
  { id: 'host_170', name: 'Katie Burke', email: 'katie.burke@example.com' },
  { id: 'host_171', name: 'Liam O\'Connor', email: 'liam.oconnor@example.com' },
  { id: 'host_172', name: 'Marina Silva', email: 'marina.silva@example.com' },
  { id: 'host_173', name: 'Nolan Reed', email: 'nolan.reed@example.com' },
  { id: 'host_174', name: 'Opal Johnson', email: 'opal.johnson@example.com' },
  { id: 'host_175', name: 'Parker Mills', email: 'parker.mills@example.com' },
  { id: 'host_176', name: 'Quinn Foster', email: 'quinn.foster@example.com' },
  { id: 'host_177', name: 'Raven Black', email: 'raven.black@example.com' },
  { id: 'host_178', name: 'Skylar Blue', email: 'skylar.blue@example.com' },
  { id: 'host_179', name: 'Troy Harper', email: 'troy.harper@example.com' },
  { id: 'host_180', name: 'Unity Collective', email: 'unity@example.com' },
  { id: 'host_181', name: 'Vance Motors', email: 'vance@example.com' },
  { id: 'host_182', name: 'Wade Wilson', email: 'wade.wilson@example.com' },
  { id: 'host_183', name: 'Xena Warrior', email: 'xena.warrior@example.com' },
  { id: 'host_184', name: 'York Enterprises', email: 'york@example.com' },
  { id: 'host_185', name: 'Zara Ahmed', email: 'zara.ahmed@example.com' },
  { id: 'host_186', name: 'Arlo James', email: 'arlo.james@example.com' },
  { id: 'host_187', name: 'Bianca Rossi', email: 'bianca.rossi@example.com' },
  { id: 'host_188', name: 'Cade Hunter', email: 'cade.hunter@example.com' },
  { id: 'host_189', name: 'Delilah Rose', email: 'delilah.rose@example.com' },
  { id: 'host_190', name: 'Emmett Brown', email: 'emmett.brown@example.com' },
  { id: 'host_191', name: 'Freya Nordic', email: 'freya.nordic@example.com' },
  { id: 'host_192', name: 'Griffin Stone', email: 'griffin.stone@example.com' },
  { id: 'host_193', name: 'Haven Motors', email: 'haven@example.com' },
  { id: 'host_194', name: 'Ivan Petrov', email: 'ivan.petrov@example.com' },
  { id: 'host_195', name: 'Jade Emperor', email: 'jade.emperor@example.com' },
  { id: 'host_196', name: 'Knox Security', email: 'knox@example.com' },
  { id: 'host_197', name: 'Luna Motors', email: 'luna@example.com' },
  { id: 'host_198', name: 'Magnus Power', email: 'magnus.power@example.com' },
  { id: 'host_199', name: 'Nova Star', email: 'nova.star@example.com' },
  { id: 'host_200', name: 'Onyx Black', email: 'onyx.black@example.com' }
]

// Rest of your constants remain the same...
export const FEATURES_LIST = [
  'Apple CarPlay',
  'Android Auto',
  'Bluetooth',
  'Premium Sound',
  'Leather Seats',
  'Heated Seats',
  'Cooled Seats',
  'Navigation',
  'Backup Camera',
  '360 Camera',
  'Parking Sensors',
  'Adaptive Cruise Control',
  'Lane Keep Assist',
  'Blind Spot Monitoring',
  'Sport Mode',
  'Carbon Fiber Interior',
  'Panoramic Sunroof',
  'Convertible',
  'All-Wheel Drive',
  '4-Wheel Drive',
  'Autopilot',
  'Night Vision',
  'Heads Up Display',
  'Massage Seats',
  'Third Row Seating',
  'Tow Package',
  'Roof Rack',
  'Keyless Entry',
  'Remote Start',
  'WiFi Hotspot'
]

export const BADGE_TYPES = [
  'Superhost',
  'All-Star Host',
  'Quick Response',
  'Top Rated',
  'Verified',
  'Elite',
  'Premium Fleet',
  'Instant Book',
  'Free Delivery',
  'Airport Pickup'
]

export const DEFAULT_RULES = "No smoking. Must be 25+ to book. Valid driver's license and insurance required. 200 miles/day included, $3/mile after."

export const CITIES_ARIZONA = [
  'Phoenix',
  'Scottsdale',
  'Tempe',
  'Mesa',
  'Chandler',
  'Gilbert',
  'Glendale',
  'Peoria',
  'Surprise',
  'Paradise Valley',
  'Cave Creek',
  'Fountain Hills'
]

export const COMMON_LUXURY_MODELS = [
  { make: 'Lamborghini', model: 'Huracan' },
  { make: 'Lamborghini', model: 'Aventador' },
  { make: 'Ferrari', model: '488 Spider' },
  { make: 'Ferrari', model: 'F8 Tributo' },
  { make: 'McLaren', model: '720S' },
  { make: 'McLaren', model: '570S' },
  { make: 'Porsche', model: '911 Turbo S' },
  { make: 'Rolls-Royce', model: 'Ghost' },
  { make: 'Bentley', model: 'Continental GT' },
  { make: 'Mercedes-Benz', model: 'AMG GT' },
  { make: 'BMW', model: 'M8' },
  { make: 'Audi', model: 'R8' },
  { make: 'Tesla', model: 'Model S Plaid' },
  { make: 'Tesla', model: 'Model X' },
  { make: 'Range Rover', model: 'Sport SVR' }
]