-- AlterTable
ALTER TABLE "platform_settings" ADD COLUMN     "defaultCommissionRate" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN     "insurancePlatformShare" DOUBLE PRECISION NOT NULL DEFAULT 0.30,
ADD COLUMN     "processingFeeFixed" DOUBLE PRECISION NOT NULL DEFAULT 1.50,
ADD COLUMN     "processingFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 0.035,
ADD COLUMN     "tier1CommissionRate" DOUBLE PRECISION NOT NULL DEFAULT 0.20,
ADD COLUMN     "tier1VehicleThreshold" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "tier2CommissionRate" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
ADD COLUMN     "tier2VehicleThreshold" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "tier3CommissionRate" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
ADD COLUMN     "tier3VehicleThreshold" INTEGER NOT NULL DEFAULT 100;
