// app/partner/settings/components/index.ts
export { AccountTab } from './AccountTab'
export { CompanyTab } from './CompanyTab'
export { BankingTab } from './BankingTab'
export { SecurityTab } from './SecurityTab'
export { NotificationsTab } from './NotificationsTab'
export { PrivacyTab } from './PrivacyTab'
export { AgreementTab } from './AgreementTab'
export { DeleteAccountModal } from './DeleteAccountModal'
export { default as AvailabilityTab } from './AvailabilityTab'
